### DISCUSSION TITLE
v1.1.0 🌈

### DISCUSSION THREAD

**Discussion by kamiazya** [ts-graphviz/setup-graphviz#342] [General]
**Full Changelog**: https://github.com/ts-graphviz/setup-graphviz/compare/v1.0.1...v1.1.0

Added support for strict version specification feature in Ubuntu and Windows(non-macos) Runner.

```yaml
- uses: ts-graphviz/setup-graphviz@v1
  with:
    ubuntu-graphviz-version: '2.42.2-3build2'
    ubuntu-libgraphvizdev-version: '2.42.2-3build2'
    windows-graphviz-version: '2.49.3'
```

Special thanks for @stunney :sparkles:

<hr /><em>This discussion was created from the release <a href='https://github.com/ts-graphviz/setup-graphviz/releases/tag/v1.1.0'>v1.1.0 🌈</a>.</em>
