### DISCUSSION TITLE
v1.2.0 🌈

### DISCUSSION THREAD

**Discussion by kamiazya** [ts-graphviz/setup-graphviz#462] [General]
**Full Changelog**: https://github.com/ts-graphviz/setup-graphviz/compare/v1.1...v1.2.0

## Add skip repository update flag

A flag to specify whether or not to update the package manager's repositories, allowing users to arbitrarily choose whether or not to update.

This fixes the following issues(#457).

```yaml
- name: Setup Graphviz
  uses: ts-graphviz/setup-graphviz@v1
  with:
    # Skip to run apt update command on Ubuntu.
    ubuntu-skip-apt-update: 'true' # defalt false
    # Skip to run brew update command on macOS.
    macos-skip-brew-update: 'true' # defalt false
```

Special thanks for @jbms and @mvrueden :sparkles:

<hr /><em>This discussion was created from the release <a href='https://github.com/ts-graphviz/setup-graphviz/releases/tag/v1.2.0'>v1.2.0 🌈</a>.</em>
